SELECT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM PLACES JOIN (SELECT HOST_ID,COUNT(HOST_ID) 
FROM PLACES
GROUP BY HOST_ID
HAVING COUNT(HOST_ID) > 1
ORDER BY ID) AS T
ON PLACES.HOST_ID = T.HOST_ID
ORDER BY 1
