SELECT USER_ID, NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ",STREET_ADDRESS2) AS 전체주소, CONCAT(LEFT(TLNO,3), "-",MID(TLNO,4,4),"-",RIGHT(TLNO,4)) AS 전화번호
FROM USED_GOODS_USER T1 
JOIN (SELECT WRITER_ID, COUNT(*)  AS CNT 
FROM USED_GOODS_BOARD 
GROUP BY WRITER_ID
HAVING CNT  > 2) T2
ON T1.USER_ID = T2.WRITER_ID
ORDER BY 1 DESC
