SELECT A.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
FROM MEMBER_PROFILE A 
JOIN (
    SELECT COUNT(*) AS T, MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY 1 DESC
    LIMIT 1 ) B 
ON A.MEMBER_ID = B.MEMBER_ID
JOIN (
 SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM REST_REVIEW
) C
ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY 3,2
