SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE  + INTERVAL 1 DAY, START_DATE)), 1) AS AVERRAGE_DURATION 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATEDIFF(END_DATE  + INTERVAL 1 DAY, START_DATE)) >= 7
ORDER BY 2 DESC, 1 DESC
