SELECT DATE_FORMAT(START_DATE, '%m') AS MONTH, CAR_ID ,count(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE between '2022-08-01' and '2022-10-31' AND CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE between '2022-08-01' and '2022-10-31' GROUP BY CAR_ID HAVING COUNT(*) > 4) 
GROUP BY CAR_ID, DATE_FORMAT(START_DATE, '%m')
ORDER BY 1, 2 DESC
