SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER a JOIN 
(select WRITER_ID, PRICE
    from USED_GOODS_BOARD
WHERE STATUS = 'DONE'
) 
as b
ON a.USER_ID = b.WRITER_ID
GROUP BY USER_ID HAVING TOTAL_SALES >= 700000
ORDER BY 3 
