SELECT CONCAT('/home/grep/src/', F1.BOARD_ID,'/',FILE_ID,FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F1
JOIN
(SELECT BOARD_ID
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC
LIMIT 1) AS F2
ON F1.BOARD_ID = F2.BOARD_ID
ORDER BY F1.FILE_ID DESC
